#!/bin/bash -ex
# Highly opinionated wrapper for Arch Linux packaging (mainly for scx-scheds: https://github.com/sched-ext/scx)

exec meson setup \
  --prefix        /usr \
  --libexecdir    lib \
  --sbindir       bin \
  --buildtype     release \
  --auto-features auto \
  --wrap-mode     nodownload \
  -D              b_pie=true \
  -D              python.bytecompile=1 \
  "$@"
